"use client";

import { useEffect, useState } from "react";
import { AdminTopBar } from "@/components/layout/AdminTopBar";
import { apiClient } from "@/lib/api";
import { Html5QrcodeScanner } from "html5-qrcode";

export default function QRScanner() {
    const [scanResult, setScanResult] = useState<string | null>(null);
    const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
    const [message, setMessage] = useState("");

    useEffect(() => {
        let scanner: Html5QrcodeScanner | null = null;

        if (!scanResult) {
            scanner = new Html5QrcodeScanner(
                "reader",
                { fps: 10, qrbox: { width: 250, height: 250 } },
                false
            );

            scanner.render(onScanSuccess, onScanFailure);
        }

        return () => {
            if (scanner) {
                scanner.clear().catch(error => console.error("Failed to clear scanner", error));
            }
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [scanResult]);

    const onScanSuccess = async (decodedText: string) => {
        setScanResult(decodedText);
        verifyQR(decodedText);
    };

    const onScanFailure = () => {
        // Just ignore continuous failures from seeking
    };

    const verifyQR = async (token: string) => {
        setStatus("loading");
        setMessage("Verifying QR code...");

        try {
            const data = await apiClient<{ userId: string }>("/api/verify-qr", {
                method: "POST",
                body: JSON.stringify({ token })
            });

            setStatus("success");
            setMessage(`Verified successfully! User ID: ${data.userId}`);

            // Automatically reset after 3 seconds
            setTimeout(() => {
                resetScanner();
            }, 3000);

        } catch (err: unknown) {
            setStatus("error");
            setMessage(err instanceof Error ? err.message : "Failed to verify QR code");
        }
    };

    const resetScanner = () => {
        setScanResult(null);
        setStatus("idle");
        setMessage("");
    };

    return (
        <div className="flex-1 overflow-y-auto w-full h-full pb-8 flex flex-col items-center">
            <AdminTopBar title="QR Scanner" />

            <div className="px-4 py-8 w-full flex flex-col items-center">
                <h1 className="text-xl font-bold mb-2">Scan Student QR</h1>
                <p className="text-slate-500 text-sm mb-6 text-center">
                    Point the camera at the QR code generated by the student&apos;s app.
                </p>

                {!scanResult && (
                    <div id="reader" className="w-full max-w-sm rounded-2xl overflow-hidden shadow-lg mb-6 border-2 border-slate-100"></div>
                )}

                {scanResult && (
                    <div className="w-full max-w-sm bg-white dark:bg-zinc-800 p-6 rounded-3xl shadow-lg border border-slate-100 dark:border-zinc-700 flex flex-col items-center text-center">
                        {status === "loading" && (
                            <span className="material-symbols-outlined text-5xl text-blue-500 animate-spin mb-4">refresh</span>
                        )}
                        {status === "success" && (
                            <span className="material-symbols-outlined text-5xl text-green-500 mb-4">check_circle</span>
                        )}
                        {status === "error" && (
                            <span className="material-symbols-outlined text-5xl text-red-500 mb-4">error</span>
                        )}

                        <h3 className={`text-xl font-bold mb-2 ${status === "success" ? "text-green-600" :
                            status === "error" ? "text-red-600" : "text-slate-900 dark:text-white"
                            }`}>
                            {status === "success" ? "Verification OK" :
                                status === "error" ? "Invalid QR" : "Processing..."}
                        </h3>

                        <p className="text-slate-600 dark:text-slate-400 mb-6">{message}</p>

                        {status === "error" && (
                            <button
                                onClick={resetScanner}
                                className="w-full bg-slate-900 text-white font-bold h-12 rounded-xl hover:bg-slate-800 transition-colors"
                            >
                                Try Again
                            </button>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
